name: Release

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["linux", "darwin"]
        arch: ["arm64", "amd64"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o automate-semver-${{ matrix.os }}-${{ matrix.arch }}
      - name: Archive build output artifact
        uses: actions/upload-artifact@v3
        with:
          name: automate-semver-${{ matrix.os }}-${{ matrix.arch }}
          path: automate-semver-${{ matrix.os }}-${{ matrix.arch }}
          retention-days: 1
  create-new-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Fetch all repository details (Including tag for semver).
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Determan new version by using Semver logic.
      - name: Semver Release
        id: semver_rel
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Download all artifacts"
        uses: actions/download-artifact@v3

      - name: "Release by using action-automatic-releases"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{steps.semver_rel.outputs.new_tag}}
          title: ${{steps.semver_rel.outputs.new_tag}}
          prerelease: false
          files: |
            **/automate-semver-*
